FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/quarkus-app/lib/ /app/lib/
COPY --from=build /app/target/quarkus-app/*.jar /app/
COPY --from=build /app/target/quarkus-app/app/ /app/app/
COPY --from=build /app/target/quarkus-app/quarkus/ /app/quarkus/

ENV DB_HOST=mysql
ENV DB_PORT=3306
ENV DB_NAME=immo
ENV DB_USER=root
ENV DB_PASSWORD=root

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/quarkus-run.jar"]